@startuml EyesOfDeathGod
class Printer {
	Texture2D _quadTex
    void SendToFaceApi()
    void CvtToRed()
}

class FaceDetector {
    Mat Detect(webcamMat)
}

class FaceApiManager {
    IReadOnlyList<Face> Faces
    void GetAge(byte[])
}

Printer --> FaceDetector
Printer --> FaceApiManager
@enduml